- hosts: localhost
  become: yes
  tasks:

  - name: Remove a container
    docker_container:
      name: closjarjart
      keep_volumes: true
      state: absent

  - name: Create closjarjart data folder
    file:
      path: /data/closjarjart/docker
      state: directory

  - name: Create closjarjart volume
    community.docker.docker_volume:
      name: closjarjart_data

  - name: Delete Dockerfile
    file:
      path: /data/closjarjart/docker/Dockerfile
      state: absent

  - name: Write docker file
    ansible.builtin.blockinfile:
      path: /data/closjarjart/docker/Dockerfile
      create: true
      mode: a+rwx
      block: |
        FROM node:22.14-alpine3.21
        RUN apk update
        RUN apk add wget
        RUN mkdir -p /opt/closjarjart
        WORKDIR /opt/closjarjart/
        RUN wget https://github.com/Zombitch/closjarjart/archive/refs/heads/main.zip
        RUN unzip main.zip && rm -f main.zip
        WORKDIR /opt/closjarjart/closjarjart-main/closjarjart-back
        RUN echo "encodingLoop=5" >> .env
        RUN echo "cryptKey={{ cryptKey }}" >> .env
        RUN echo "jwtSecret={{ secret }}" >> .env
        RUN echo "apiKey={{ apiKey }}" >> .env
        RUN echo "mongoPassword={{ mongoPassword }}" >> .env
        RUN echo "smtpUser={{ smtpUser }}" >> .env
        RUN echo "smtpPwd={{ smtpPassword }}" >> .env
        RUN echo "allowOrigin={{ allowOrigin }}" >> .env
        RUN npm install -g @nestjs/cli
        RUN npm i
        EXPOSE 4000
        CMD ["npm","start"]
      state: present

  - name: Delete previous image
    community.docker.docker_image:
      name: closjarjart-back
      state: absent
      force_absent: true

  - name: Create the image
    community.docker.docker_image:
      name: closjarjart-back
      source: build
      build:
        path: /data/closjarjart-back/docker

  - name: Run navssi/tools container
    community.docker.docker_container:
      container_default_behavior: no_defaults
      name: closjarjart-back
      image: closjarjart-back
      hostname: closjarjart-back_host
      state: started
      restart_policy: always
      exposed_ports :
        - 4000
      volumes:
        - closjarjart_data:/opt/closjarjart/closjarjart-main/closjarjart-back/data
      networks:
        - name: "{{ network }}"